# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"

matrix:
  allow_failures:
    - nodejs_version: "0.11"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
  - npm install -g grunt-cli

test_script:
  - node --version
  - npm --version
  - ps: npm test
  - cmd: npm test

build: off

version: "{build}"